fix: simplify `takeScreenshot` logic

diff --git a/moonblast b/moonblast
--- a/moonblast
+++ b/moonblast
@@ -185,19 +185,28 @@ check() {
   echo "   $COMMAND: $RESULT"
 }
 
+GRIM_ARGS=(
+  "${CURSOR:+-c}"
+  "${SCALE:+-s "$SCALE"}"
+)
+
 takeScreenshot() {
   FILE=$1
   mkdir -p "$(dirname "$FILE")"
   GEOM=$2
   OUTPUT=$3
-  if [ -n "$OUTPUT" ]; then
-    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
-  elif [ -z "$GEOM" ]; then
-    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} "$FILE" || die "Unable to invoke grim"
-  else
-    grim ${CURSOR:+-c} ${SCALE:+-s "$SCALE"} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
+
+  [[ -n "$OUTPUT" ]] && {
+    grim ${GRIM_ARGS[@]} -o "$OUTPUT" "$FILE" || die "Unable to invoke grim"
+    return 0
+  }
+  [[ -n "$GEOM" ]] && {
+    grim ${GRIM_ARGS[@]} -g "$GEOM" "$FILE" || die "Unable to invoke grim"
     resetFade
-  fi
+    return 0
+  }
+
+  grim ${GRIM_ARGS[@]} "$FILE" || die "Unable to invoke grim"
 }
 
 wait() {
